/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.UI.NhanVien;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import src.Model.BangLuong;
import src.Model.BangLuongNhanVien;
import src.Model.CaLam;
import src.Model.ChiNhanh;
import src.Model.CongViec;
import src.Model.HinhAnh;
import src.Model.LichLamViec;
import src.Model.LichLamViecCaLam;
import src.Model.NhanVien;
import src.Model.PhieuLuong;
import src.Model.PhieuNhapHang;
import src.Service.BangLuongNhanVienService;
import src.Service.BangLuongService;
import src.Service.CaLamService;
import src.Service.ChiNhanhServive;
import src.Service.CongViecService;
import src.Service.HinhAnhService;
import src.Service.LichLamViecCaLamService;
import src.Service.LichLamViecService;
import src.Service.NhanVienService;
import src.Service.PhieuLuongService;
import src.UI.HangHoa.Frame_ThemHangHoa;
import src.Util.Util;

/**
 *
 * @author WINDOWS 10
 */
public class Frame_ThemNhanVien extends javax.swing.JFrame {
    private ChiNhanh chiNhanh;
    private NhanVienService nhanVienService = new NhanVienService();
    private ChiNhanhServive chiNhanhService = new ChiNhanhServive();
    private HinhAnhService hinhAnhService = new HinhAnhService();
    private CongViecService congViecService = new CongViecService();
    
    String destinationFolderPath = "D:\\tai_lieu_tren_lop\\LapTrinhTienTien\\Workspace\\Git_GarageOtoAnt_DoAn\\GarageOto_JavaSwingAnt\\DoAn_GarageOto_Ant\\src\\image";
    private String imageLink = "";
    List<TableColumn> originalColumns = new ArrayList<>();
    private Util util = new Util();
    private NhanVien nhanVienDangNhap;
    /**
     * Creates new form frame_ThemKhachHang
     */
    public Frame_ThemNhanVien(ChiNhanh chiNhanh, NhanVien nhanVienDangNhap) {
        initComponents();
        this.nhanVienDangNhap = nhanVienDangNhap;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.chiNhanh = chiNhanh;
        try {
            List<ChiNhanh> danhSachChiNhanh = chiNhanhService.hienThiTatCaChiNhanh();
            cbChiTietNhanVien_chiNhanhLamViec.removeAllItems();
            for (ChiNhanh chiNhanhItem: danhSachChiNhanh){
                cbChiTietNhanVien_chiNhanhLamViec.addItem(chiNhanhItem.getMaChiNhanh() + " " + chiNhanhItem.getTenChiNhanh());
            }
            List<CongViec> danhSachCongViec = congViecService.hienThiTatCaCongViec();
            cbChiTietNhanVien_chucDanh.removeAllItems();
            for (CongViec congViec: danhSachCongViec){
                cbChiTietNhanVien_chucDanh.addItem(congViec.getMaCongViec() + " " + congViec.getTenCongViec());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Frame_ThemNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbChiTietNhanVien_tenChiNhanh3.setText(chiNhanh.getTenChiNhanh());

        int soNhanVien = 0;
        try {
            soNhanVien = nhanVienService.demSoNhanVien();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_ThemNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfChiTietNhanVien_ma.setText("NV0" + String.valueOf(soNhanVien + 1));
        tfChiTietNhanVien_ma.setEnabled(false);
        
        
    }

    public Frame_ThemNhanVien() {
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btnGroup_gioiTinh = new javax.swing.ButtonGroup();
        jPanel103 = new javax.swing.JPanel();
        jPanel104 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        lbChiTietNhanVien_tenChiNhanh3 = new javax.swing.JLabel();
        jPanel87 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        panelAnh1 = new javax.swing.JPanel();
        lbChiTietNhanVien_anh = new javax.swing.JLabel();
        jPanel105 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        radioChiTietNhanVien_nu = new javax.swing.JRadioButton();
        radioChiTietNhanVien_nam = new javax.swing.JRadioButton();
        dateChooserChiTietNhanVien_ngaySinh = new com.toedter.calendar.JDateChooser();
        jPanel106 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        tfChiTietNhanVien_ma = new javax.swing.JTextField();
        jPanel107 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        tfChiTietNhanVien_ten = new javax.swing.JTextField();
        jPanel108 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        tfChiTietNhanVien_diaChi = new javax.swing.JTextField();
        jPanel109 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        tfChiTietNhanVien_soDienThoai = new javax.swing.JTextField();
        jPanel110 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        tfChiTietNhanVien_cccd = new javax.swing.JTextField();
        jPanel111 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        cbChiTietNhanVien_chucDanh = new javax.swing.JComboBox<>();
        jPanel113 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        cbChiTietNhanVien_chiNhanhLamViec = new javax.swing.JComboBox<>();
        panelhihi1 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        tfChiTietNhanVien_maSoThue = new javax.swing.JTextField();
        btnChiTietNhanVien_chonAnh = new javax.swing.JButton();
        btnChiTietNhanVien_capNhat = new javax.swing.JButton();
        btnChiTietNhanVien_thoat = new javax.swing.JButton();
        jPanel114 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        cbChiTietNhanVien_trangThai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel103.setBackground(new java.awt.Color(255, 255, 255));
        jPanel103.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel104.setBackground(new java.awt.Color(255, 255, 255));

        jLabel76.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(153, 153, 153));
        jLabel76.setText("Chi nhánh tạo:");

        lbChiTietNhanVien_tenChiNhanh3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbChiTietNhanVien_tenChiNhanh3.setForeground(new java.awt.Color(153, 153, 153));
        lbChiTietNhanVien_tenChiNhanh3.setText("Chi nhánh trung tâm");

        javax.swing.GroupLayout jPanel104Layout = new javax.swing.GroupLayout(jPanel104);
        jPanel104.setLayout(jPanel104Layout);
        jPanel104Layout.setHorizontalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel104Layout.createSequentialGroup()
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbChiTietNhanVien_tenChiNhanh3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel104Layout.setVerticalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel104Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbChiTietNhanVien_tenChiNhanh3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 390, 30));

        jPanel87.setBackground(new java.awt.Color(255, 255, 255));
        jPanel87.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel87.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setBackground(new java.awt.Color(255, 255, 255));
        jLabel68.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel68.setText("Thông tin nhân viên");
        jPanel87.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel103.add(jPanel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 150, 30));

        javax.swing.GroupLayout panelAnh1Layout = new javax.swing.GroupLayout(panelAnh1);
        panelAnh1.setLayout(panelAnh1Layout);
        panelAnh1Layout.setHorizontalGroup(
            panelAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbChiTietNhanVien_anh, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelAnh1Layout.setVerticalGroup(
            panelAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbChiTietNhanVien_anh, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel103.add(panelAnh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 48, 80, 80));

        jPanel105.setBackground(new java.awt.Color(255, 255, 255));
        jPanel105.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel77.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel77.setText("Ngày sinh");

        btnGroup_gioiTinh.add(radioChiTietNhanVien_nu);
        radioChiTietNhanVien_nu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        radioChiTietNhanVien_nu.setText("Nữ");

        btnGroup_gioiTinh.add(radioChiTietNhanVien_nam);
        radioChiTietNhanVien_nam.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        radioChiTietNhanVien_nam.setText("Nam");

        dateChooserChiTietNhanVien_ngaySinh.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel105Layout = new javax.swing.GroupLayout(jPanel105);
        jPanel105.setLayout(jPanel105Layout);
        jPanel105Layout.setHorizontalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel105Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(dateChooserChiTietNhanVien_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioChiTietNhanVien_nam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioChiTietNhanVien_nu)
                .addContainerGap())
        );
        jPanel105Layout.setVerticalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel105Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioChiTietNhanVien_nu)
                    .addComponent(dateChooserChiTietNhanVien_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel77)
                        .addComponent(radioChiTietNhanVien_nam)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 370, 40));

        jPanel106.setBackground(new java.awt.Color(255, 255, 255));
        jPanel106.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel78.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel78.setText("Mã nhân viên");

        tfChiTietNhanVien_ma.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfChiTietNhanVien_ma.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfChiTietNhanVien_ma.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel106Layout = new javax.swing.GroupLayout(jPanel106);
        jPanel106.setLayout(jPanel106Layout);
        jPanel106Layout.setHorizontalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel106Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChiTietNhanVien_ma, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel106Layout.setVerticalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel106Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(tfChiTietNhanVien_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 48, 370, 30));

        jPanel107.setBackground(new java.awt.Color(255, 255, 255));
        jPanel107.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel86.setText("Tên nhân viên");

        tfChiTietNhanVien_ten.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfChiTietNhanVien_ten.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfChiTietNhanVien_ten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel107Layout = new javax.swing.GroupLayout(jPanel107);
        jPanel107.setLayout(jPanel107Layout);
        jPanel107Layout.setHorizontalGroup(
            jPanel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel107Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChiTietNhanVien_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel107Layout.setVerticalGroup(
            jPanel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel107Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(tfChiTietNhanVien_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 370, 30));

        jPanel108.setBackground(new java.awt.Color(255, 255, 255));
        jPanel108.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel87.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel87.setText("Địa chỉ");

        tfChiTietNhanVien_diaChi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfChiTietNhanVien_diaChi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfChiTietNhanVien_diaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel108Layout = new javax.swing.GroupLayout(jPanel108);
        jPanel108.setLayout(jPanel108Layout);
        jPanel108Layout.setHorizontalGroup(
            jPanel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel108Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChiTietNhanVien_diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel108Layout.setVerticalGroup(
            jPanel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel108Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(tfChiTietNhanVien_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 370, 30));

        jPanel109.setBackground(new java.awt.Color(255, 255, 255));
        jPanel109.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel88.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel88.setText("Điện thoại");

        tfChiTietNhanVien_soDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfChiTietNhanVien_soDienThoai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfChiTietNhanVien_soDienThoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel109Layout = new javax.swing.GroupLayout(jPanel109);
        jPanel109.setLayout(jPanel109Layout);
        jPanel109Layout.setHorizontalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel109Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChiTietNhanVien_soDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel109Layout.setVerticalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel109Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(tfChiTietNhanVien_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 370, 40));

        jPanel110.setBackground(new java.awt.Color(255, 255, 255));
        jPanel110.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel89.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel89.setText("CMND/CCCD");

        tfChiTietNhanVien_cccd.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfChiTietNhanVien_cccd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfChiTietNhanVien_cccd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel110Layout = new javax.swing.GroupLayout(jPanel110);
        jPanel110.setLayout(jPanel110Layout);
        jPanel110Layout.setHorizontalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel110Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(tfChiTietNhanVien_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel110Layout.setVerticalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel110Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(tfChiTietNhanVien_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 370, 30));

        jPanel111.setBackground(new java.awt.Color(255, 255, 255));
        jPanel111.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel91.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel91.setText("Chức danh");

        cbChiTietNhanVien_chucDanh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cbChiTietNhanVien_chucDanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên sơn", "Nhân viên sữa chữa", "Nhân viên kỹ thuật", "Bảo vệ", "Kế toán viên", "Admin" }));

        javax.swing.GroupLayout jPanel111Layout = new javax.swing.GroupLayout(jPanel111);
        jPanel111.setLayout(jPanel111Layout);
        jPanel111Layout.setHorizontalGroup(
            jPanel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel111Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cbChiTietNhanVien_chucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel111Layout.setVerticalGroup(
            jPanel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel111Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(cbChiTietNhanVien_chucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 370, 40));

        jPanel113.setBackground(new java.awt.Color(255, 255, 255));
        jPanel113.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel92.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel92.setText("Chi nhánh làm việc");

        cbChiTietNhanVien_chiNhanhLamViec.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel113Layout = new javax.swing.GroupLayout(jPanel113);
        jPanel113.setLayout(jPanel113Layout);
        jPanel113Layout.setHorizontalGroup(
            jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel113Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel92)
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel113Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(cbChiTietNhanVien_chiNhanhLamViec, 0, 215, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel113Layout.setVerticalGroup(
            jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel113Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel92)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel113Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(cbChiTietNhanVien_chiNhanhLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel103.add(jPanel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 370, 40));

        panelhihi1.setBackground(new java.awt.Color(255, 255, 255));
        panelhihi1.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel93.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel93.setText("Mã số thuế");

        tfChiTietNhanVien_maSoThue.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfChiTietNhanVien_maSoThue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfChiTietNhanVien_maSoThue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panelhihi1Layout = new javax.swing.GroupLayout(panelhihi1);
        panelhihi1.setLayout(panelhihi1Layout);
        panelhihi1Layout.setHorizontalGroup(
            panelhihi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhihi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(tfChiTietNhanVien_maSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelhihi1Layout.setVerticalGroup(
            panelhihi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhihi1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelhihi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93)
                    .addComponent(tfChiTietNhanVien_maSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(panelhihi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 370, 30));

        btnChiTietNhanVien_chonAnh.setBackground(new java.awt.Color(0, 51, 255));
        btnChiTietNhanVien_chonAnh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnChiTietNhanVien_chonAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietNhanVien_chonAnh.setText("Chọn ảnh");
        btnChiTietNhanVien_chonAnh.setBorder(null);
        btnChiTietNhanVien_chonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietNhanVien_chonAnhActionPerformed(evt);
            }
        });
        jPanel103.add(btnChiTietNhanVien_chonAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 31));

        btnChiTietNhanVien_capNhat.setBackground(new java.awt.Color(0, 204, 0));
        btnChiTietNhanVien_capNhat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnChiTietNhanVien_capNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietNhanVien_capNhat.setText("Thêm");
        btnChiTietNhanVien_capNhat.setBorder(null);
        btnChiTietNhanVien_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietNhanVien_capNhatActionPerformed(evt);
            }
        });
        jPanel103.add(btnChiTietNhanVien_capNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 100, 31));

        btnChiTietNhanVien_thoat.setBackground(new java.awt.Color(51, 51, 255));
        btnChiTietNhanVien_thoat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnChiTietNhanVien_thoat.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietNhanVien_thoat.setText("Thoát");
        btnChiTietNhanVien_thoat.setBorder(null);
        btnChiTietNhanVien_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietNhanVien_thoatActionPerformed(evt);
            }
        });
        jPanel103.add(btnChiTietNhanVien_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 100, 31));

        jPanel114.setBackground(new java.awt.Color(255, 255, 255));
        jPanel114.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel94.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel94.setText("Trạng thái");

        cbChiTietNhanVien_trangThai.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cbChiTietNhanVien_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "Ngừng làm việc" }));

        javax.swing.GroupLayout jPanel114Layout = new javax.swing.GroupLayout(jPanel114);
        jPanel114.setLayout(jPanel114Layout);
        jPanel114Layout.setHorizontalGroup(
            jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel114Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cbChiTietNhanVien_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel114Layout.setVerticalGroup(
            jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel114Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel94)
                    .addComponent(cbChiTietNhanVien_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel103.add(jPanel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 370, 40));

        getContentPane().add(jPanel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiTietNhanVien_chonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietNhanVien_chonAnhActionPerformed
        layTenFile();
        lbChiTietNhanVien_anh.setIcon(null);
        File file;
        try {
            file = new File(imageLink);
            BufferedImage originalImage = ImageIO.read(file);
            Image scaledImage = originalImage.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaledImage);
            lbChiTietNhanVien_anh.setIcon(icon);

        } catch (MalformedURLException ex) {
            Logger.getLogger(Frame_ChiTietNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Frame_ChiTietNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChiTietNhanVien_chonAnhActionPerformed

    private void btnChiTietNhanVien_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietNhanVien_capNhatActionPerformed
        NhanVien nhanVien = new NhanVien();
        nhanVien.setMaNhanVien(tfChiTietNhanVien_ma.getText());
        nhanVien.setCccd(tfChiTietNhanVien_cccd.getText());
        nhanVien.setChucDanh(cbChiTietNhanVien_chucDanh.getSelectedItem().toString().split(" ")[0]);
        if (radioChiTietNhanVien_nam.isSelected()){
            nhanVien.setGioiTinh("Nam");
        } else {
            nhanVien.setGioiTinh("Nữ");
        }
        nhanVien.setNgaySinh(util.localDateParseMethodToLocalDate(util.layNgayString(dateChooserChiTietNhanVien_ngaySinh.getDate())));
        nhanVien.setSoDienThoai(tfChiTietNhanVien_soDienThoai.getText());
        nhanVien.setTenNhanVien(tfChiTietNhanVien_ten.getText());
        nhanVien.setTrangThai(cbChiTietNhanVien_trangThai.getSelectedItem().toString());
        nhanVien.setMaChiNhanh(cbChiTietNhanVien_chiNhanhLamViec.getSelectedItem().toString().split(" ")[0]);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
        Date date = new Date();  
        nhanVien.setNgayBatDauLamViec(util.localDateParseMethodToLocalDate(String.valueOf(formatter.format(date))));
            nhanVien.setTaoBoiMaNhanVien(nhanVienDangNhap.getMaNhanVien());
            nhanVien.setNoLuong(0);
        nhanVien.setDiaChi(tfChiTietNhanVien_diaChi.getText());
        nhanVien.setMaSoThue(tfChiTietNhanVien_maSoThue.getText());
        try {
            nhanVienService.themNhanVien(nhanVien);
        } catch (SQLException ex) {
            Logger.getLogger(Frame_ChiTietNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (lbChiTietNhanVien_anh.getIcon() != null){
            saveImage(imageLink, destinationFolderPath);
            HinhAnh hinhAnh = new HinhAnh();
            try {
                int temp = hinhAnhService.demSoHinhAnh() + 1;
                hinhAnh.setMaHinhAnh("HA0"+ temp);
            } catch (SQLException ex) {
                Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            hinhAnh.setNoiDung(nhanVien.getTenNhanVien());
            String[] parts = imageLink.split("\\\\");
            hinhAnh.setTenHinh(parts[parts.length - 1]);
            hinhAnh.setMaNhanVien(nhanVien.getMaNhanVien());
            try {
                HinhAnh hinhAnhDb = hinhAnhService.hienThiHinhAnhTheoMaNhanVien(nhanVien.getMaNhanVien());
                if (hinhAnhDb.getMaHinhAnh() == null){
                    hinhAnhService.themHinhAnh(hinhAnh);
                } else {
                    hinhAnh.setMaHinhAnh(hinhAnhDb.getMaHinhAnh());
                    hinhAnhService.updateHinhAnh(hinhAnh);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnChiTietNhanVien_capNhatActionPerformed

    private void btnChiTietNhanVien_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietNhanVien_thoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnChiTietNhanVien_thoatActionPerformed
    public void saveImage(String sourceImagePath, String destinationFolderPath) {
        try {
            // Create a Path object for the source image
            Path sourcePath = Paths.get(sourceImagePath);

            // Create a Path object for the destination folder
            Path destinationFolder = Paths.get(destinationFolderPath);

            // Ensure the destination folder exists, create it if it doesn't
            Files.createDirectories(destinationFolder);

            // Get the file name of the source image
            String fileName = sourcePath.getFileName().toString();

            // Create a Path object for the destination image file
            Path destinationFilePath = destinationFolder.resolve(fileName);

            // Copy the source image file to the destination folder
            Files.copy(sourcePath, destinationFilePath);

            System.out.println("Image saved successfully to: " + destinationFilePath);
        } catch (IOException e) {
            System.err.println("Error saving image: " + e.getMessage());
        }
    }        private void layTenFile(){
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("", "jpg"));
        chooser.setFileFilter(chooser.getChoosableFileFilters()[1]);
        int r = chooser.showDialog(this,null);
        if (r!= JFileChooser.APPROVE_OPTION) return;
        File file = new File(chooser.getSelectedFile() + chooser.getFileFilter().getDescription());
        imageLink = file.getPath();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_ThemNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietNhanVien_capNhat;
    private javax.swing.JButton btnChiTietNhanVien_chonAnh;
    private javax.swing.JButton btnChiTietNhanVien_thoat;
    private javax.swing.ButtonGroup btnGroup_gioiTinh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbChiTietNhanVien_chiNhanhLamViec;
    private javax.swing.JComboBox<String> cbChiTietNhanVien_chucDanh;
    private javax.swing.JComboBox<String> cbChiTietNhanVien_trangThai;
    private com.toedter.calendar.JDateChooser dateChooserChiTietNhanVien_ngaySinh;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel106;
    private javax.swing.JPanel jPanel107;
    private javax.swing.JPanel jPanel108;
    private javax.swing.JPanel jPanel109;
    private javax.swing.JPanel jPanel110;
    private javax.swing.JPanel jPanel111;
    private javax.swing.JPanel jPanel113;
    private javax.swing.JPanel jPanel114;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel89;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JLabel lbChiTietNhanVien_anh;
    private javax.swing.JLabel lbChiTietNhanVien_tenChiNhanh;
    private javax.swing.JLabel lbChiTietNhanVien_tenChiNhanh1;
    private javax.swing.JLabel lbChiTietNhanVien_tenChiNhanh3;
    private javax.swing.JPanel panelAnh1;
    private javax.swing.JPanel panelhihi1;
    private javax.swing.JRadioButton radioChiTietNhanVien_nam;
    private javax.swing.JRadioButton radioChiTietNhanVien_nu;
    private javax.swing.JTextField tfChiTietNhanVien_cccd;
    private javax.swing.JTextField tfChiTietNhanVien_diaChi;
    private javax.swing.JTextField tfChiTietNhanVien_ma;
    private javax.swing.JTextField tfChiTietNhanVien_maSoThue;
    private javax.swing.JTextField tfChiTietNhanVien_soDienThoai;
    private javax.swing.JTextField tfChiTietNhanVien_ten;
    // End of variables declaration//GEN-END:variables
}
