/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.UI.HangHoa;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import src.Model.HangHoa;
import src.Model.HinhAnh;
import src.Model.NhomHang;
import src.Service.HangHoaService;
import src.Service.HinhAnhService;
import src.Service.NhomHangService;

/**
 *
 * @author WINDOWS 10
 */
public class Frame_ThemHangHoa extends javax.swing.JFrame {
    private HangHoaService hangHoaSerive = new HangHoaService();
    private NhomHangService nhomHangService = new NhomHangService();
    private HinhAnhService hinhAnhService = new HinhAnhService();
    String destinationFolderPath = "D:\\tai_lieu_tren_lop\\LapTrinhTienTien\\Workspace\\Git_GarageOtoAnt_DoAn\\GarageOto_JavaSwingAnt\\DoAn_GarageOto_Ant\\src\\image";
    /**
     * Creates new form frame_ThemHangHoa
     */
    public Frame_ThemHangHoa() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            tfThemHangHoa_maHang.setText("HH0" + (hangHoaSerive.demSoHangHoa()+1)) ;
        } catch (SQLException ex) {
            Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            hienThiDanhSachMaNhomHang();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel63 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel64 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        tfThemHangHoa_maHang = new javax.swing.JTextField();
        jPanel68 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        tfThemHangHoa_tenHang = new javax.swing.JTextField();
        jPanel69 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        cbThemHangHoa_maNhomHang = new javax.swing.JComboBox<>();
        jPanel70 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        tfThemHangHoa_loaiHang = new javax.swing.JTextField();
        jPanel72 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        tfThemHangHoa_giaBan = new javax.swing.JTextField();
        jPanel73 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        tfThemHangHoa_giaVon = new javax.swing.JTextField();
        btnThemHangHoa_themHinhAnh = new javax.swing.JButton();
        btnThemHangHoa_thoat = new javax.swing.JButton();
        jPanel79 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        btnThemHangHoa_luu = new javax.swing.JButton();
        lbThemHangHoa_hinhAnh3 = new javax.swing.JLabel();
        lbThemHangHoa_hinhAnh1 = new javax.swing.JLabel();
        lbThemHangHoa_hinhAnh2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel51.setText("Thêm dịch vụ");

        javax.swing.GroupLayout jPanel63Layout = new javax.swing.GroupLayout(jPanel63);
        jPanel63.setLayout(jPanel63Layout);
        jPanel63Layout.setHorizontalGroup(
            jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel63Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel63Layout.setVerticalGroup(
            jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel64.setBackground(new java.awt.Color(255, 255, 255));
        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel66.setBackground(new java.awt.Color(255, 255, 255));
        jPanel66.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel52.setText("Mã hàng:");

        tfThemHangHoa_maHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tfThemHangHoa_maHang.setEnabled(false);

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemHangHoa_maHang, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel66Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(tfThemHangHoa_maHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel64.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 30));

        jPanel68.setBackground(new java.awt.Color(255, 255, 255));
        jPanel68.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel54.setText("Tên hàng:");

        tfThemHangHoa_tenHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel68Layout = new javax.swing.GroupLayout(jPanel68);
        jPanel68.setLayout(jPanel68Layout);
        jPanel68Layout.setHorizontalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel68Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfThemHangHoa_tenHang, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel68Layout.setVerticalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel68Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(tfThemHangHoa_tenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel64.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        jPanel69.setBackground(new java.awt.Color(255, 255, 255));
        jPanel69.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel55.setText("Dịch vụ:");
        jLabel55.setToolTipText("");

        cbThemHangHoa_maNhomHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel69Layout = new javax.swing.GroupLayout(jPanel69);
        jPanel69.setLayout(jPanel69Layout);
        jPanel69Layout.setHorizontalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel69Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbThemHangHoa_maNhomHang, 0, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel69Layout.setVerticalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel69Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(cbThemHangHoa_maNhomHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel64.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 30));

        jPanel70.setBackground(new java.awt.Color(255, 255, 255));
        jPanel70.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel56.setText("Loại hàng:");

        tfThemHangHoa_loaiHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfThemHangHoa_loaiHang, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(tfThemHangHoa_loaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel64.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, 30));

        jPanel72.setBackground(new java.awt.Color(255, 255, 255));
        jPanel72.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel58.setText("Giá bán:");

        tfThemHangHoa_giaBan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfThemHangHoa_giaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThemHangHoa_giaBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel72Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemHangHoa_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel72Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(tfThemHangHoa_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel64.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 380, 30));

        jPanel73.setBackground(new java.awt.Color(255, 255, 255));
        jPanel73.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel59.setText("Giá vốn:");

        tfThemHangHoa_giaVon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfThemHangHoa_giaVon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThemHangHoa_giaVonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel73Layout = new javax.swing.GroupLayout(jPanel73);
        jPanel73.setLayout(jPanel73Layout);
        jPanel73Layout.setHorizontalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemHangHoa_giaVon, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel73Layout.setVerticalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(tfThemHangHoa_giaVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel64.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 380, 30));

        btnThemHangHoa_themHinhAnh.setBackground(new java.awt.Color(255, 153, 153));
        btnThemHangHoa_themHinhAnh.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnThemHangHoa_themHinhAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHangHoa_themHinhAnh.setText("Thêm hình ảnh");
        btnThemHangHoa_themHinhAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHangHoa_themHinhAnhActionPerformed(evt);
            }
        });
        jPanel64.add(btnThemHangHoa_themHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, -1));

        btnThemHangHoa_thoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThemHangHoa_thoat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnThemHangHoa_thoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHangHoa_thoat.setText("Thoát");
        btnThemHangHoa_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHangHoa_thoatActionPerformed(evt);
            }
        });
        jPanel64.add(btnThemHangHoa_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 80, -1));

        jPanel79.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel79Layout = new javax.swing.GroupLayout(jPanel79);
        jPanel79.setLayout(jPanel79Layout);
        jPanel79Layout.setHorizontalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel79Layout.setVerticalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel64.add(jPanel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel60.setText("Hình ảnh:");
        jPanel64.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, -1));

        btnThemHangHoa_luu.setBackground(new java.awt.Color(0, 204, 51));
        btnThemHangHoa_luu.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnThemHangHoa_luu.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHangHoa_luu.setText("Lưu");
        btnThemHangHoa_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHangHoa_luuActionPerformed(evt);
            }
        });
        jPanel64.add(btnThemHangHoa_luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 80, -1));

        lbThemHangHoa_hinhAnh3.setToolTipText("");
        lbThemHangHoa_hinhAnh3.setBorder(new javax.swing.border.MatteBorder(null));
        lbThemHangHoa_hinhAnh3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemHangHoa_hinhAnh3MouseClicked(evt);
            }
        });
        jPanel64.add(lbThemHangHoa_hinhAnh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, 90));

        lbThemHangHoa_hinhAnh1.setToolTipText("");
        lbThemHangHoa_hinhAnh1.setBorder(new javax.swing.border.MatteBorder(null));
        lbThemHangHoa_hinhAnh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemHangHoa_hinhAnh1MouseClicked(evt);
            }
        });
        jPanel64.add(lbThemHangHoa_hinhAnh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 90));

        lbThemHangHoa_hinhAnh2.setToolTipText("");
        lbThemHangHoa_hinhAnh2.setBorder(new javax.swing.border.MatteBorder(null));
        lbThemHangHoa_hinhAnh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemHangHoa_hinhAnh2MouseClicked(evt);
            }
        });
        jPanel64.add(lbThemHangHoa_hinhAnh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, 90));

        jTabbedPane3.addTab("Thông tin", jPanel64);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfThemHangHoa_giaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThemHangHoa_giaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThemHangHoa_giaBanActionPerformed

    private void tfThemHangHoa_giaVonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThemHangHoa_giaVonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThemHangHoa_giaVonActionPerformed
    
    List<String> danhSachLinkHinhAnh = new ArrayList<>();
    private void btnThemHangHoa_themHinhAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHangHoa_themHinhAnhActionPerformed
        layTenFile();
        hienThiHanhAnh(danhSachLinkHinhAnh);
    }//GEN-LAST:event_btnThemHangHoa_themHinhAnhActionPerformed

    private void btnThemHangHoa_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHangHoa_thoatActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "MySQL Connector",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnThemHangHoa_thoatActionPerformed

    private void btnThemHangHoa_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHangHoa_luuActionPerformed
        HangHoa hangHoa = new HangHoa();
        hangHoa.setMaHangHoa(tfThemHangHoa_maHang.getText());
        hangHoa.setGiaBan(Double.parseDouble(tfThemHangHoa_giaBan.getText()));
        hangHoa.setGiaVon(Double.parseDouble(tfThemHangHoa_giaVon.getText()));
        hangHoa.setKhachDat(Short.parseShort("0"));
        hangHoa.setTonKho(Short.parseShort("0"));
        hangHoa.setTenHangHoa(tfThemHangHoa_tenHang.getText());
        hangHoa.setLoaiHang(tfThemHangHoa_loaiHang.getText());
        hangHoa.setMaNhomHang(cbThemHangHoa_maNhomHang.getSelectedItem().toString().split("\\s+")[0]);
        
        try {
            hangHoaSerive.themHangHoa(hangHoa);
        } catch (SQLException ex) {
            Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String linkHinhAnh : danhSachLinkHinhAnh){
            saveImage(linkHinhAnh, destinationFolderPath);
            HinhAnh hinhAnh = new HinhAnh();
            try {
                int temp = hinhAnhService.demSoHinhAnh() + 1;
                hinhAnh.setMaHinhAnh("HA0"+ temp);
            } catch (SQLException ex) {
                Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            hinhAnh.setNoiDung(hangHoa.getTenHangHoa());
            String[] parts = linkHinhAnh.split("\\\\");
            hinhAnh.setTenHinh(parts[parts.length - 1]);
            hinhAnh.setMaHangHoa(hangHoa.getMaHangHoa());
            try {
                System.out.println("hihi");
                int a =  hinhAnhService.themHinhAnh(hinhAnh);
                System.out.println(a);
            } catch (SQLException ex) {
                Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemHangHoa_luuActionPerformed

    private void lbThemHangHoa_hinhAnh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemHangHoa_hinhAnh1MouseClicked
        try{
            danhSachLinkHinhAnh.remove(0);
            for(String link: danhSachLinkHinhAnh){
                System.out.println(link);
                hienThiHanhAnh(danhSachLinkHinhAnh);
            }
        } catch (Exception ex){
            hienThiHanhAnh(danhSachLinkHinhAnh);
        }
    }//GEN-LAST:event_lbThemHangHoa_hinhAnh1MouseClicked

    private void lbThemHangHoa_hinhAnh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemHangHoa_hinhAnh2MouseClicked
        try{
            danhSachLinkHinhAnh.remove(1);
            for(String link: danhSachLinkHinhAnh){
                System.out.println(link);
                hienThiHanhAnh(danhSachLinkHinhAnh);
            }
        } catch (Exception ex){
            hienThiHanhAnh(danhSachLinkHinhAnh);
        }
    }//GEN-LAST:event_lbThemHangHoa_hinhAnh2MouseClicked

    private void lbThemHangHoa_hinhAnh3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemHangHoa_hinhAnh3MouseClicked
        try{
            danhSachLinkHinhAnh.remove(2);
            for(String link: danhSachLinkHinhAnh){
                System.out.println(link);
                hienThiHanhAnh(danhSachLinkHinhAnh);
            }
        } catch (Exception ex){
            hienThiHanhAnh(danhSachLinkHinhAnh);
        }
    }//GEN-LAST:event_lbThemHangHoa_hinhAnh3MouseClicked
    private void layTenFile(){
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("", "jpg"));
        chooser.setFileFilter(chooser.getChoosableFileFilters()[1]);
        int r = chooser.showDialog(this,null);
        if (r!= JFileChooser.APPROVE_OPTION) return;
        File file = new File(chooser.getSelectedFile() + chooser.getFileFilter().getDescription());
        danhSachLinkHinhAnh.add(file.getPath());
    }
    
    public void saveImage(String sourceImagePath, String destinationFolderPath) {
        try {
            // Create a Path object for the source image
            Path sourcePath = Paths.get(sourceImagePath);
            
            // Create a Path object for the destination folder
            Path destinationFolder = Paths.get(destinationFolderPath);
            
            // Ensure the destination folder exists, create it if it doesn't
            Files.createDirectories(destinationFolder);
            
            // Get the file name of the source image
            String fileName = sourcePath.getFileName().toString();
            
            // Create a Path object for the destination image file
            Path destinationFilePath = destinationFolder.resolve(fileName);
            
            // Copy the source image file to the destination folder
            Files.copy(sourcePath, destinationFilePath);
            
            System.out.println("Image saved successfully to: " + destinationFilePath);
        } catch (IOException e) {
            System.err.println("Error saving image: " + e.getMessage());
        }
    }
    private void hienThiHanhAnh(List<String> danhSachLinkHinhAnh){
        lbThemHangHoa_hinhAnh1.setIcon(null);
        lbThemHangHoa_hinhAnh2.setIcon(null);
        lbThemHangHoa_hinhAnh3.setIcon(null);
        String lb_hienThiHinhAnh = "lbThemHangHoa_hinhAnh";
        int i =1;
        for(String linkHinhAnh : danhSachLinkHinhAnh){
            File file;
            try {
                file = new File(linkHinhAnh);
                BufferedImage originalImage = ImageIO.read(file);
                Image scaledImage = originalImage.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(scaledImage);
                if (i == 1){
                    lbThemHangHoa_hinhAnh1.setIcon(icon);
                }
                if (i == 2){
                    lbThemHangHoa_hinhAnh2.setIcon(icon);
                }
                if (i == 3){
                    lbThemHangHoa_hinhAnh3.setIcon(icon);
                }
                i++;
                
            } catch (MalformedURLException ex) {
                Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void hienThiDanhSachMaNhomHang() throws SQLException{
        List<NhomHang> danhSachNhomHang = new ArrayList<>();
        cbThemHangHoa_maNhomHang.removeAllItems();
        danhSachNhomHang = nhomHangService.hienThiTatCaNhomHang();
        for (NhomHang nhomHang : danhSachNhomHang){
            cbThemHangHoa_maNhomHang.addItem(nhomHang.getMaNhomHang() + " " + nhomHang.getTenNhomHang());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_ThemHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_ThemHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemHangHoa_luu;
    private javax.swing.JButton btnThemHangHoa_themHinhAnh;
    private javax.swing.JButton btnThemHangHoa_thoat;
    private javax.swing.JComboBox<String> cbThemHangHoa_maNhomHang;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lbThemHangHoa_hinhAnh1;
    private javax.swing.JLabel lbThemHangHoa_hinhAnh2;
    private javax.swing.JLabel lbThemHangHoa_hinhAnh3;
    private javax.swing.JTextField tfThemHangHoa_giaBan;
    private javax.swing.JTextField tfThemHangHoa_giaVon;
    private javax.swing.JTextField tfThemHangHoa_loaiHang;
    private javax.swing.JTextField tfThemHangHoa_maHang;
    private javax.swing.JTextField tfThemHangHoa_tenHang;
    // End of variables declaration//GEN-END:variables
}
