/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.UI.NhaCungCap;
import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import src.Model.NhaCungCap;
import src.Model.NhanVien;
import src.Service.NhaCungCapService;
import src.Util.Util;

/**
 *
 * @author WINDOWS 10
 */
public class Frame_XemChiTietCapNhatNhaCungCap extends javax.swing.JFrame {
    private Util util = new Util();
    private NhaCungCapService nhaCungCapService = new NhaCungCapService();
    private NhaCungCap nhaCungCap;
    
    private NhanVien nhanVienDangNhap;

    /**
     * Creates new form frame_ThemNhaCungCap
     */
    public Frame_XemChiTietCapNhatNhaCungCap(NhaCungCap nhaCungCap, NhanVien nhanVien) {
        initComponents();
        this.nhanVienDangNhap = nhanVien;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.nhaCungCap = nhaCungCap;
        tfThemNhaCungCap_diaChi.setEnabled(false);
        tfThemNhaCungCap_dienThoai.setEnabled(false);
        tfThemNhaCungCap_email.setEnabled(false);
        tfThemNhaCungCap_ma.setEnabled(false);
        tfThemNhaCungCap_maSoThue.setEnabled(false);
        tfThemNhaCungCap_ten.setEnabled(false);
        
        tfThemNhaCungCap_diaChi.setText(nhaCungCap.getDiaChi());
        tfThemNhaCungCap_dienThoai.setText(nhaCungCap.getSoDienThoai());
        tfThemNhaCungCap_email.setText(nhaCungCap.getEmail());
        tfThemNhaCungCap_ma.setText(nhaCungCap.getMaNhaCungCap());
        tfThemNhaCungCap_maSoThue.setText(nhaCungCap.getMaSoThue());
        tfThemNhaCungCap_ten.setText(nhaCungCap.getTenNhaCungCap());
    }

    public Frame_XemChiTietCapNhatNhaCungCap() {
    }
    

    public NhaCungCap getNhaCungCap() {
        return nhaCungCap;
    }

    public void setNhaCungCap(NhaCungCap nhaCungCap) {
        this.nhaCungCap = nhaCungCap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel88 = new javax.swing.JPanel();
        jPanel87 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanel86 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        btnThemNhaCungCap_luu = new javax.swing.JButton();
        jPanel94 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        tfThemNhaCungCap_ma = new javax.swing.JTextField();
        jPanel95 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        tfThemNhaCungCap_ten = new javax.swing.JTextField();
        jPanel96 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        tfThemNhaCungCap_diaChi = new javax.swing.JTextField();
        jPanel97 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        tfThemNhaCungCap_dienThoai = new javax.swing.JTextField();
        jPanel113 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        tfThemNhaCungCap_email = new javax.swing.JTextField();
        jPanel128 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        tfThemNhaCungCap_maSoThue = new javax.swing.JTextField();
        btnThemNhaCungCap_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel88.setBackground(new java.awt.Color(242, 249, 255));
        jPanel88.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel87.setBackground(new java.awt.Color(242, 249, 255));

        jLabel68.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(153, 153, 153));
        jLabel68.setText("Chi nhánh tạo:");

        jLabel69.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(153, 153, 153));
        jLabel69.setText("Chi nhánh trung tâm");

        javax.swing.GroupLayout jPanel87Layout = new javax.swing.GroupLayout(jPanel87);
        jPanel87.setLayout(jPanel87Layout);
        jPanel87Layout.setHorizontalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel87Layout.createSequentialGroup()
                .addComponent(jLabel68)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel69)
                .addGap(0, 70, Short.MAX_VALUE))
        );
        jPanel87Layout.setVerticalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel87Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel88.add(jPanel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 290, 30));

        jPanel86.setBackground(new java.awt.Color(242, 249, 255));
        jPanel86.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel86.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel67.setText("Thêm nhà cung cấp");
        jPanel86.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jPanel88.add(jPanel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 140, 30));

        btnThemNhaCungCap_luu.setBackground(new java.awt.Color(0, 102, 255));
        btnThemNhaCungCap_luu.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnThemNhaCungCap_luu.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNhaCungCap_luu.setText("Cập nhật");
        btnThemNhaCungCap_luu.setBorder(null);
        btnThemNhaCungCap_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhaCungCap_luuActionPerformed(evt);
            }
        });
        jPanel88.add(btnThemNhaCungCap_luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 31));

        jPanel94.setBackground(new java.awt.Color(242, 249, 255));
        jPanel94.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel72.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel72.setText("Mã nhà cung cấp");

        tfThemNhaCungCap_ma.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfThemNhaCungCap_ma.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel94Layout = new javax.swing.GroupLayout(jPanel94);
        jPanel94.setLayout(jPanel94Layout);
        jPanel94Layout.setHorizontalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel94Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(tfThemNhaCungCap_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel94Layout.setVerticalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel94Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(tfThemNhaCungCap_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel88.add(jPanel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 370, 30));

        jPanel95.setBackground(new java.awt.Color(242, 249, 255));
        jPanel95.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel79.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel79.setText("Tên nhà cung cấp");

        tfThemNhaCungCap_ten.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfThemNhaCungCap_ten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel95Layout = new javax.swing.GroupLayout(jPanel95);
        jPanel95.setLayout(jPanel95Layout);
        jPanel95Layout.setHorizontalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel95Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemNhaCungCap_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel95Layout.setVerticalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel95Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79)
                    .addComponent(tfThemNhaCungCap_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel88.add(jPanel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 370, 30));

        jPanel96.setBackground(new java.awt.Color(242, 249, 255));
        jPanel96.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel80.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel80.setText("Địa chỉ");

        tfThemNhaCungCap_diaChi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfThemNhaCungCap_diaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel96Layout = new javax.swing.GroupLayout(jPanel96);
        jPanel96.setLayout(jPanel96Layout);
        jPanel96Layout.setHorizontalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel96Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemNhaCungCap_diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel96Layout.setVerticalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel96Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(tfThemNhaCungCap_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel88.add(jPanel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 370, 30));

        jPanel97.setBackground(new java.awt.Color(242, 249, 255));
        jPanel97.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel81.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel81.setText("Điện thoại");

        tfThemNhaCungCap_dienThoai.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfThemNhaCungCap_dienThoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel97Layout = new javax.swing.GroupLayout(jPanel97);
        jPanel97.setLayout(jPanel97Layout);
        jPanel97Layout.setHorizontalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel97Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemNhaCungCap_dienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel97Layout.setVerticalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel97Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(tfThemNhaCungCap_dienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel88.add(jPanel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 370, 40));

        jPanel113.setBackground(new java.awt.Color(242, 249, 255));
        jPanel113.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel86.setText("Email");

        tfThemNhaCungCap_email.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfThemNhaCungCap_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel113Layout = new javax.swing.GroupLayout(jPanel113);
        jPanel113.setLayout(jPanel113Layout);
        jPanel113Layout.setHorizontalGroup(
            jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel113Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemNhaCungCap_email, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel113Layout.setVerticalGroup(
            jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel113Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(tfThemNhaCungCap_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel88.add(jPanel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 370, 40));

        jPanel128.setBackground(new java.awt.Color(242, 249, 255));
        jPanel128.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel90.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel90.setText("Mã số thuế");

        tfThemNhaCungCap_maSoThue.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tfThemNhaCungCap_maSoThue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel128Layout = new javax.swing.GroupLayout(jPanel128);
        jPanel128.setLayout(jPanel128Layout);
        jPanel128Layout.setHorizontalGroup(
            jPanel128Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel128Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfThemNhaCungCap_maSoThue, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel128Layout.setVerticalGroup(
            jPanel128Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel128Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel128Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(tfThemNhaCungCap_maSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel88.add(jPanel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 370, 30));

        btnThemNhaCungCap_thoat.setBackground(new java.awt.Color(153, 153, 153));
        btnThemNhaCungCap_thoat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnThemNhaCungCap_thoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNhaCungCap_thoat.setText("Bỏ qua");
        btnThemNhaCungCap_thoat.setBorder(null);
        btnThemNhaCungCap_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhaCungCap_thoatActionPerformed(evt);
            }
        });
        jPanel88.add(btnThemNhaCungCap_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 100, 31));

        getContentPane().add(jPanel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 850, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    int a = 0;
    private void btnThemNhaCungCap_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhaCungCap_thoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThemNhaCungCap_thoatActionPerformed

    private void btnThemNhaCungCap_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhaCungCap_luuActionPerformed
        if (!util.kiemTraTonTaiChuoi(nhanVienDangNhap.getPhanQuyen(), " 9.3 ")){
                JOptionPane.showMessageDialog(this, "Bạn không có quyền cập nhật thông tin nhà cung cấp!");
                return;
            }
        if (btnThemNhaCungCap_luu.getText().equals("Cập nhật")){
            btnThemNhaCungCap_luu.setText("Lưu");
            tfThemNhaCungCap_diaChi.setEnabled(true);
            tfThemNhaCungCap_dienThoai.setEnabled(true);
            tfThemNhaCungCap_email.setEnabled(true);
            tfThemNhaCungCap_maSoThue.setEnabled(true);
            tfThemNhaCungCap_ten.setEnabled(true);
        } else {
            NhaCungCap nhaCungCap = new NhaCungCap();
            nhaCungCap.setMaNhaCungCap(tfThemNhaCungCap_ma.getText());
            nhaCungCap.setDiaChi(tfThemNhaCungCap_diaChi.getText());
            nhaCungCap.setEmail(tfThemNhaCungCap_email.getText());
            nhaCungCap.setMaSoThue(tfThemNhaCungCap_maSoThue.getText());
            nhaCungCap.setSoDienThoai(tfThemNhaCungCap_dienThoai.getText());
            nhaCungCap.setTenNhaCungCap(tfThemNhaCungCap_ten.getText());
            
            try {
                nhaCungCapService.capNhatNhaCungCap(nhaCungCap);
            } catch (SQLException ex) {
                Logger.getLogger(Frame_XemChiTietCapNhatNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            tfThemNhaCungCap_diaChi.setEnabled(false);
            tfThemNhaCungCap_dienThoai.setEnabled(false);
            tfThemNhaCungCap_email.setEnabled(false);
            tfThemNhaCungCap_ma.setEnabled(false);
            tfThemNhaCungCap_maSoThue.setEnabled(false);
            tfThemNhaCungCap_ten.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnThemNhaCungCap_luuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_XemChiTietCapNhatNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_XemChiTietCapNhatNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_XemChiTietCapNhatNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_XemChiTietCapNhatNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_XemChiTietCapNhatNhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemNhaCungCap_luu;
    private javax.swing.JButton btnThemNhaCungCap_thoat;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel113;
    private javax.swing.JPanel jPanel128;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel88;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JPanel jPanel97;
    private javax.swing.JTextField tfThemNhaCungCap_diaChi;
    private javax.swing.JTextField tfThemNhaCungCap_dienThoai;
    private javax.swing.JTextField tfThemNhaCungCap_email;
    private javax.swing.JTextField tfThemNhaCungCap_ma;
    private javax.swing.JTextField tfThemNhaCungCap_maSoThue;
    private javax.swing.JTextField tfThemNhaCungCap_ten;
    // End of variables declaration//GEN-END:variables
}
